version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my_marvin_jenkins_new
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./my_marvin.yml:/var/jenkins_home/my_marvin.yml
      - ./jobs.groovy:/var/jenkins_home/jobs.groovy
      - ./plugins.txt:/var/jenkins_home/plugins.txt
    env_file:
      - .env
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/my_marvin.yml

    networks:
      - jenkins_network
volumes:
  jenkins_home:

networks:
  jenkins_network: